language: node_js
node_js:
  - node
  - 12
  - 14

script:
  - npm run lint
  - npm test
  - npm run coverage

after_success:
  - npm run coverage-publish

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
